name: Update AUR Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  update-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: latest

    - name: Update PKGBUILD version
      run: |
        NEW_VERSION="${{ inputs.version }}"
        sed -i "s/^pkgver=.*/pkgver=$NEW_VERSION/" PKGBUILD
        sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

    - name: Download source and generate checksum
      run: |
        # 生成源码文件
        makepkg --geninteg

    - name: Update checksums in PKGBUILD
      run: |
        # 提取checksum并更新到PKGBUILD
        CHECKSUM=$(makepkg -g | sed 's/sha256sums=/sha256sums=('/' | sed 's/$/')/')
        sed -i "/^sha256sums=/c\\$CHECKSUM" PKGBUILD

    - name: Build package
      run: |
        makepkg -s --noconfirm

    - name: Generate .SRCINFO
      run: |
        makepkg --printsrcinfo > .SRCINFO

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        VERSION="${{ inputs.version }}"
        git add PKGBUILD .SRCINFO
        git commit -m "Update to version $VERSION"
        git push